"""Browsing views over the project cards: a Markdown table and an Obsidian base."""
from __future__ import annotations

from ..config import Config
from ..links import link_to
from ..vault import atomic_write
from .model import PROJECT_FILE, Project
from .registry import Registry
from .stages import find_artifact


INDEX_FILE = "INDEX.md"
BASE_FILE = "projects.base"

PUBLISHED_MARK = "+"
PLANNED_MARK = "-"


def write_views(config: Config, registry: Registry) -> list[str]:
    """Refresh the index table and seed the Obsidian base; return what changed."""
    changed: list[str] = []
    if not registry.projects and not config.projects_root.is_dir():
        return changed  # nothing to browse yet, so nothing is created
    index = config.projects_root / INDEX_FILE
    rendered = render_index(config, registry)
    if not index.is_file() or index.read_text(encoding="utf-8") != rendered:
        atomic_write(index, rendered)
        changed.append(INDEX_FILE)
    base = config.projects_root / BASE_FILE
    if not base.exists() or _is_untouched(base):
        rendered_base = render_base(config)
        if not base.exists() or base.read_text(encoding="utf-8") != rendered_base:
            atomic_write(base, rendered_base)
            changed.append(BASE_FILE)
    return changed


# ``file.name`` keeps the extension, so comparing it to a name without one is
# false for every note in the vault. A base doing that shows an empty table,
# which reads like "nothing collected yet" rather than like a broken filter.
DEAD_FILTERS: tuple[str, ...] = (
    'file.name == "project"',
    "file.name.endsWith(",
    "file.name.startsWith(",
)


def dead_filter(base) -> str | None:
    """The filter in this base that cannot match anything, if there is one.

    Obsidian rewrites a base the first time it opens it, so a file Asterism
    generated stops matching what Asterism wrote and can no longer be repaired
    silently. Reporting it is what is left, and it is the honest thing anyway:
    the file is the person's.
    """
    try:
        text = base.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    return next((pattern for pattern in DEAD_FILTERS if pattern in text), None)


def _is_untouched(base) -> bool:
    """Whether the file is still exactly one Asterism wrote, so it may be replaced.

    Anything else is the person's: a view refined in Obsidian is never
    overwritten, which is why this compares whole files rather than guessing.
    """
    try:
        return base.read_text(encoding="utf-8") in SUPERSEDED_BASES
    except (OSError, UnicodeDecodeError):
        return False


def render_index(config: Config, registry: Registry) -> str:
    index_file = config.projects_root / INDEX_FILE
    lines = [
        "# Projects",
        "",
        "Generated by `asterism status`. Edit a project in its own card, not here.",
        "",
        "| Date | Title | Pillar | Type | Status | Platforms |",
        "|---|---|---|---|---|---|",
    ]
    for project in registry.projects:
        lines.append(
            "| {date} | {title} | {pillar} | {type} | {status} | {platforms} |".format(
                date=project.created.isoformat() if project.created else "",
                title=_title_link(config, project, index_file),
                pillar=project.pillar or "",
                type=project.type or "",
                status=project.status,
                platforms=_platforms(project),
            )
        )
    if not registry.projects:
        lines.append("| | _no projects yet_ | | | | |")
    if registry.problems:
        lines.extend(["", "## Unreadable cards", ""])
        lines.extend(f"- {problem}" for problem in registry.problems)
    return "\n".join(lines).rstrip() + "\n"


def _title_link(config: Config, project: Project, index_file) -> str:
    if project.directory is None:
        return project.title
    card = find_artifact(config.project, project.directory, PROJECT_FILE)
    relative = card.relative_to(config.vault).as_posix()
    return link_to(config.links, config.vault, relative, project.title, from_file=index_file)


def _platforms(project: Project) -> str:
    return ", ".join(
        f"{name} {PUBLISHED_MARK if project.published_on(name) else PLANNED_MARK}"
        for name in project.platforms
    )


def render_base(config: Config) -> str:
    """A starting Obsidian Bases view over the project cards.

    The filter matches on ``file.basename`` — the name without its extension,
    since ``file.name`` keeps the ``.md`` — and on nothing else. Where the
    Obsidian vault root sits is the person's choice: open the folder above an
    Asterism vault and every path gains a segment, so a filter on a folder
    matches nothing at all. The file says how to add one back.
    """
    return CURRENT_BASE


CURRENT_BASE = (
    "# Generated by Asterism once, then yours: edit it and it is never rewritten.\n"
    "#\n"
    "# The filter matches the project cards by name rather than by folder,\n"
    "# because where your Obsidian vault root sits is your choice. Narrow it\n"
    "# yourself if other notes are named like a card, for example:\n"
    '#     - file.folder.startsWith("projects")\n'
    "filters:\n"
    "  and:\n"
    '    - file.basename.endsWith("project")\n'
    "views:\n"
    "  - type: table\n"
    "    name: All projects\n"
    "    order:\n"
    "      - note.created\n"
    "      - note.title\n"
    "      - note.status\n"
    "      - note.pillar\n"
    "      - note.type\n"
    "      - note.platforms\n"
    "  - type: table\n"
    "    name: Waiting on me\n"
    "    filters:\n"
    "      and:\n"
    '        - note.status != "published"\n'
    '        - note.status != "retrospected"\n'
    '        - note.status != "dropped"\n'
    "    order:\n"
    "      - note.status\n"
    "      - note.created\n"
    "      - note.title\n"
    "      - note.promise\n"
    "  - type: table\n"
    "    name: Published\n"
    "    filters:\n"
    "      and:\n"
    '        - note.status == "published"\n'
    "    order:\n"
    "      - note.created\n"
    "      - note.title\n"
    "      - note.platforms\n"
)


# Bases files Asterism wrote itself in earlier versions. One that still matches
# byte for byte has never been edited, so replacing it cannot lose anyone's
# work. Every one of these matched nothing: the first two filtered on
# `file.name == "project"`, which stopped being true when cards became
# `01-project.md`; the third used `file.name.endsWith("project")`, and
# `file.name` keeps the extension, and also required a top-level `content`
# folder, which only exists when the Asterism vault is the Obsidian vault.
SUPERSEDED_BASES: tuple[str, ...] = (
    *(
        (
            "filters:\n"
            "  and:\n"
            '    - file.name == "project"\n'
            "views:\n"
            "  - type: table\n"
            "    name: All projects\n"
            "    order:\n"
            f"      - {prefix}created\n"
            f"      - {prefix}title\n"
            f"      - {prefix}pillar\n"
            f"      - {prefix}type\n"
            f"      - {prefix}status\n"
            "  - type: table\n"
            "    name: In flight\n"
            "    filters:\n"
            "      and:\n"
            '        - note.status != "published"\n'
            '        - note.status != "archived"\n'
            "    order:\n"
            f"      - {prefix}scheduled\n"
            f"      - {prefix}title\n"
            f"      - {prefix}status\n"
        )
        for prefix in ("note.", "")
    ),
    CURRENT_BASE.replace(
        "# Generated by Asterism once, then yours: edit it and it is never rewritten.\n"
        "#\n"
        "# The filter matches the project cards by name rather than by folder,\n"
        "# because where your Obsidian vault root sits is your choice. Narrow it\n"
        "# yourself if other notes are named like a card, for example:\n"
        '#     - file.folder.startsWith("content")\n'
        "filters:\n"
        "  and:\n"
        '    - file.basename.endsWith("project")\n',
        "filters:\n"
        "  and:\n"
        '    - file.inFolder("content")\n'
        '    - file.name.endsWith("project")\n',
    ),
)
