"""Browsing views over the project cards: a Markdown table and an Obsidian base."""
from __future__ import annotations

from ..config import Config
from ..links import link_to
from ..vault import atomic_write
from .model import PROJECT_FILE, ContentProject
from .registry import Registry
from .stages import find_artifact


INDEX_FILE = "INDEX.md"
BASE_FILE = "projects.base"

PUBLISHED_MARK = "+"
PLANNED_MARK = "-"


def write_views(config: Config, registry: Registry) -> list[str]:
    """Refresh the index table and seed the Obsidian base; return what changed."""
    changed: list[str] = []
    if not registry.projects and not config.content_root.is_dir():
        return changed  # nothing to browse yet, so nothing is created
    index = config.content_root / INDEX_FILE
    rendered = render_index(config, registry)
    if not index.is_file() or index.read_text(encoding="utf-8") != rendered:
        atomic_write(index, rendered)
        changed.append(INDEX_FILE)
    base = config.content_root / BASE_FILE
    if not base.exists():  # seeded once so edits made in Obsidian survive
        atomic_write(base, render_base(config))
        changed.append(BASE_FILE)
    return changed


def render_index(config: Config, registry: Registry) -> str:
    index_file = config.content_root / INDEX_FILE
    lines = [
        "# Projects",
        "",
        "Generated by `asterism status`. Edit a project in its own card, not here.",
        "",
        "| Date | Title | Pillar | Type | Status | Platforms |",
        "|---|---|---|---|---|---|",
    ]
    for project in registry.projects:
        lines.append(
            "| {date} | {title} | {pillar} | {type} | {status} | {platforms} |".format(
                date=project.created.isoformat() if project.created else "",
                title=_title_link(config, project, index_file),
                pillar=project.pillar or "",
                type=project.type or "",
                status=project.status,
                platforms=_platforms(project),
            )
        )
    if not registry.projects:
        lines.append("| | _no projects yet_ | | | | |")
    if registry.problems:
        lines.extend(["", "## Unreadable cards", ""])
        lines.extend(f"- {problem}" for problem in registry.problems)
    return "\n".join(lines).rstrip() + "\n"


def _title_link(config: Config, project: ContentProject, index_file) -> str:
    if project.directory is None:
        return project.title
    card = find_artifact(config.project, project.directory, PROJECT_FILE)
    relative = card.relative_to(config.vault).as_posix()
    return link_to(config.links, config.vault, relative, project.title, from_file=index_file)


def _platforms(project: ContentProject) -> str:
    return ", ".join(
        f"{name} {PUBLISHED_MARK if project.published_on(name) else PLANNED_MARK}"
        for name in project.platforms
    )


def render_base(config: Config) -> str:
    """A starting Obsidian Bases view over the project cards.

    Seeded once and never overwritten, so a view refined in Obsidian stays.
    """
    return (
        "filters:\n"
        '  and:\n'
        '    - file.name == "project"\n'
        "views:\n"
        "  - type: table\n"
        "    name: All projects\n"
        "    order:\n"
        "      - note.created\n"
        "      - note.title\n"
        "      - note.pillar\n"
        "      - note.type\n"
        "      - note.status\n"
        "  - type: table\n"
        "    name: In flight\n"
        "    filters:\n"
        "      and:\n"
        '        - note.status != "published"\n'
        '        - note.status != "archived"\n'
        "    order:\n"
        "      - note.scheduled\n"
        "      - note.title\n"
        "      - note.status\n"
    )
